### ISSUE TITLE
buffer.js:359

### ISSUE THREAD

**Issue by robooo** [mapbox/togeojson#82]
I tried convert data from openstreetmap to gpx and then tried 
togeojson myfile.osm.gpx myfile.geojson

but it throws this error 
buffer.js:359
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:359:11)
    at convert (/usr/local/lib/node_modules/togeojson/togeojson:22:61)
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at ReadStream.onend (_stream_readable.js:490:10)
    at ReadStream.g (events.js:260:16)

any ideas where is the problem?

**Comment by tmcw** [comment]
```
togeojson myfile.osm.gpx myfile.geojson
```

First thing would be following the [console utility example](https://github.com/mapbox/togeojson#using-it-as-a-console-utility) and writing

```
togeojson myfile.osm.gpx > myfile.geojson
```

instead

**Comment by robooo** [comment]
sorry i forgot 
```
togeojson myfile.osm.gpx > myfile.geojson
buffer.js:359
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:359:11)
    at convert (/usr/local/lib/node_modules/togeojson/togeojson:22:61)
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/togeojson/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at ReadStream.onend (_stream_readable.js:490:10)
    at ReadStream.g (events.js:260:16)
```

**Comment by tmcw** [comment]
@robooo can you provide the source data?

**Comment by robooo** [comment]
sorry I deleted it but it was http://download.freemap.sk/slovakia.osm/slovakia.osm.pbf converted to gpx and then tried to geojson but i know there are some errors at coordinates (if I remember right there was "point" with polygon coordinates etc.)

**Comment by tmcw** [comment]
It sounds like the conversion to GPX didn't work and toGeoJSON got a binary file.

**Comment by robooo** [comment]
I don't know how i converted it but was nice readable gpx but there were some mistakes like point got polygons coordinates... I'm sure it wasn't binary

**Comment by tmcw** [comment]
Okay, well - if you can provide an input file that triggers this bug, I can try to diagnose it; please post to this issue if you can. Otherwise, closing this issue.

**Comment by robooo** [comment]
You could close ;) had no problems with correct gpx files
